# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  vmImage: windows-2022

steps:

#- task: UiPathInstallPlatform-preview@3
#  inputs:
#    cliVersion: 'X_22.10.8418.30339'
- task: UiPathTest-preview@3
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Staging Orchestrator Preview Plugin'
    testSet: '360 demo'
    folderName: 'Modern Folder'
    testReportDestination: 'result.xml'
    traceLevel: 'Verbose'