# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: ubuntu-latest
  vmImage: windows-2022

steps:
- task: UiPathTest-preview@3
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Staging Orchestrator Preview Plugin'
    parametersFilePath: 'input.json'
    testSet: 'InputParams'
    folderName: '360° Test Suite Demo'
    testReportDestination: 'result.xml'
    traceLevel: 'Verbose'

